name: LeetDown_CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:

  build-macOS-x86_64:
    runs-on: macos-11
    steps:
    - name: envdetails
      run: ls && echo && pwd
    - uses: actions/checkout@v2
    - name: envdetails
      run: ls && echo && pwd
    - name: cleanup
      run: rm -rf __MACOSX/ build
    - name: pod install
      run: pod install
    - name: build
      run: xcodebuild -workspace LeetDown.xcworkspace -scheme LeetDown_M CONFIGURATION_BUILD_DIR=/Users/runner/work/LeetDown/LeetDown
    - name: envdetails2
      run: ls && echo && pwd
    - name: zip
      run: zip -r LD_Actions_x86_64.zip LeetDown.app
    - name: release
      id: release
      uses: actions/upload-artifact@v2
      with:
        name: actions-release-macOS
        path: /Users/runner/work/LeetDown/LeetDown/LD_Actions_x86_64.zip
