name: LeetDown_CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:

  build-macOS-x86_64:
    runs-on: macos-11
    steps:
    - name: envdetails
      run: ls && echo && pwd
    - uses: actions/checkout@v2
    - name: envdetails
      run: ls && echo && pwd
    - name: cleanup
      run: rm -rf __MACOSX/ build
    - name: pod install
      run: pod install
    - name: build
      run: xcodebuild -workspace LeetDown.xcworkspace -scheme LeetDown_M CONFIGURATION_BUILD_DIR=/Users/runner/work/LeetDown/LeetDown
    - name: envdetails2
      run: ls && echo && pwd
    - name: install create-dmg
      run: brew install create-dmg
    - name: create nightly dmg
      run: create-dmg --window-size 430 270 --app-drop-link 300 0 --icon LeetDown.app 100 0 LeetDown_nightly.dmg LeetDown.app
    - name: release
      id: release
      uses: actions/upload-artifact@v2
      with:
        name: actions-release-macOS
        path: /Users/runner/work/LeetDown/LeetDown/LeetDown_nightly.dmg
